/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation CreateDepartment($payload: CreateDepartmentInput!) {\n    createDepartment(payload: $payload) {\n      message\n    }\n  }\n": typeof types.CreateDepartmentDocument,
    "\n  mutation UpdateDepartment($updateDepartmentId: String!, $payload: UpdateDepartmentInput!) {\n    updateDepartment(id: $updateDepartmentId, payload: $payload) {\n      message\n    }\n  }\n": typeof types.UpdateDepartmentDocument,
    "\n    mutation DeleteDepartment($deleteDepartmentId: String!) {\n        deleteDepartment(id: $deleteDepartmentId) {\n            message\n        }\n    }\n": typeof types.DeleteDepartmentDocument,
    "\n  mutation CreateEvent($payload: CreateEventInput!) {\n    createEvent(payload: $payload) {\n      message\n    }\n  }\n": typeof types.CreateEventDocument,
    "\n  mutation UpdateEvent($updateEventId: String!, $payload: UpdateEventInput!) {\n    updateEvent(id: $updateEventId, payload: $payload) {\n      message\n    }\n  }\n": typeof types.UpdateEventDocument,
    "\n  mutation DeleteEvent($deleteEventId: String!) {\n    deleteEvent(id: $deleteEventId) {\n      message\n    }\n  }\n": typeof types.DeleteEventDocument,
    "\n  mutation CreatePost($payload: CreatePostInput!) {\n    createPost(payload: $payload) {\n      message\n    }\n  }\n": typeof types.CreatePostDocument,
    "\n  mutation UpdatePost($data: UpdatePostInput!, $postId: String!) {\n    updatePost(data: $data, postId: $postId) {\n      message\n    }\n  }\n": typeof types.UpdatePostDocument,
    "\n  mutation DeletePost($postId: String!) {\n    deletePost(postId: $postId) {\n      message\n    }\n  }\n": typeof types.DeletePostDocument,
    "\n    mutation UpdateProfile($updateProfileId: String!, $payload: UpdateProfileInput!) {\n        updateProfile(id: $updateProfileId, payload: $payload) {\n            message\n        }\n    }\n": typeof types.UpdateProfileDocument,
    "\n  mutation CreateTicket($payload: CreateTicketInput!) {\n    createTicket(payload: $payload) {\n      message\n    }\n  }\n": typeof types.CreateTicketDocument,
    "\n  mutation UpdateTicket(\n    $updateTicketId: String!\n    $payload: UpdateTicketInput!\n  ) {\n    updateTicket(id: $updateTicketId, payload: $payload) {\n      message\n    }\n  }\n": typeof types.UpdateTicketDocument,
    "\n  mutation DeleteTicket($deleteTicketId: String!) {\n    deleteTicket(id: $deleteTicketId) {\n      message\n    }\n  }\n": typeof types.DeleteTicketDocument,
    "\n  # mutation Mutation($signInInput: SignInInput!) {\n  #   signin(signInInput: $signInInput) {\n  #     accessToken\n  #   }\n  # }\n  mutation Mutation($signInInput: SignInInput!) {\n    signin(signInInput: $signInInput) {\n      user {\n        id\n        role\n        profile {\n          id\n          firstName\n          middleName\n          lastName\n        }\n      }\n      isSignedIn\n    }\n  }\n": typeof types.MutationDocument,
    "\n  mutation LogOut {\n    logOut {\n      message\n    }\n  }\n": typeof types.LogOutDocument,
    "\n  mutation CreateUser($payload: CreateUserInput!) {\n    createUser(payload: $payload) {\n      message\n    }\n  }\n": typeof types.CreateUserDocument,
    "\n  mutation UpdateUser($updateUserId: String!, $payload: UpdateUserInput!) {\n    updateUser(id: $updateUserId, payload: $payload) {\n      message\n    }\n  }\n": typeof types.UpdateUserDocument,
    "\n  mutation DeleteUser($deleteUserId: String!) {\n    deleteUser(id: $deleteUserId) {\n      message\n    }\n  }\n": typeof types.DeleteUserDocument,
    "\n  query GetCensusSummary {\n    getCensusSummary {\n      departmentsWithUserCount {\n        departmentId\n        departmentName\n        userCount\n        departmentDescription\n      }\n      ticketsByStatus {\n        count\n        status\n      }\n      totalEvents\n      totalDepartments\n      totalTickets\n      totalUsers\n      totalPosts\n    }\n  }\n": typeof types.GetCensusSummaryDocument,
    "\n  query GetTicketData($userId: String!) {\n    getCensusSummary(userId: $userId) {\n      ticketByUserId {\n        status\n        count\n      }\n      totalTicketsByUserId\n    }\n  }\n": typeof types.GetTicketDataDocument,
    "\n  query FindAllDepartments($page: Int, $perPage: Int) {\n    findAllDepartments(page: $page, perPage: $perPage) {\n      data {\n        description\n        id\n        name\n        createdAt\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": typeof types.FindAllDepartmentsDocument,
    "\n  query FindAllForDropdown {\n    findAllForDropdown {\n      id\n      name\n      description\n    }\n  }\n": typeof types.FindAllForDropdownDocument,
    "\n  query FindAllEvents($page: Int, $perPage: Int) {\n    findAllEvents(page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        detailsUrl\n        endDate\n        id\n        location\n        startDate\n        title\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": typeof types.FindAllEventsDocument,
    "\n  query FindAllPosts($page: Int, $perPage: Int) {\n    findAllPosts(page: $page, perPage: $perPage) {\n      data {\n        datePosted\n        content\n        id\n        images\n        user {\n          id\n          profile {\n            lastName\n            firstName\n            avatar\n          }\n          department {\n            name\n            description\n          }\n          username\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": typeof types.FindAllPostsDocument,
    "\n  query FindAllTickets($where: TicketWhereInput, $page: Int, $perPage: Int) {\n    findAllTickets(where: $where, page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n        floor\n        subject\n        remarks\n        message\n        id\n        missedAt\n        screenshot\n        statusFormatted\n        status\n        updatedBy\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": typeof types.FindAllTicketsDocument,
    "\n  query FindTicketsByUser($userId: String!, $perPage: Int, $page: Int) {\n    findTicketsByUser(userId: $userId, perPage: $perPage, page: $page) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        floor\n        id\n        subject\n        statusFormatted\n        remarks\n        missedAt\n        screenshot\n        status\n        updatedBy\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": typeof types.FindTicketsByUserDocument,
    "\n  query FindTicketLogs($findTicketbyIdId: String!) {\n    findTicketbyID(id: $findTicketbyIdId) {\n      auditLogs {\n        action\n        ticketId\n        timestamp\n        updatedBy\n        remarks\n        id\n      }\n    }\n  }\n": typeof types.FindTicketLogsDocument,
    "\n  query FindTicketsWorkedByUser($userId: String!) {\n    findTicketsWorkedByUser(userId: $userId) {\n      data {\n        subject\n        status\n        statusFormatted\n        missedAt\n        remarks\n        message\n        screenshot\n        updatedBy\n        id\n        floor\n        createdById\n        createdAt\n        createdBy {\n          username\n          profile {\n            firstName\n            lastName\n          }\n        }\n      }\n    }\n  }\n": typeof types.FindTicketsWorkedByUserDocument,
    "\n  query FindTicketsByDepartment($page: Int, $perPage: Int, $search: String) {\n    findTicketsByDepartment(page: $page, perPage: $perPage, search: $search) {\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n      data {\n        id\n        subject\n        message\n        status\n        statusFormatted\n        createdAt\n        updatedAt\n        missedAt\n        remarks\n        screenshot\n        floor\n        createdBy {\n          username\n          profile {\n            firstName\n            middleName\n            lastName\n          }\n        }\n        createdById\n        updatedBy\n        departmentId\n        department {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n": typeof types.FindTicketsByDepartmentDocument,
    "\n  query FindAllUsers($page: Int, $perPage: Int) {\n      findAllUsers(perPage: $perPage, page: $page) {\n        data {\n        email\n        id\n        role\n        username\n        createdAt\n        department {\n          name\n          id\n        }\n        profile {\n          firstName\n          lastName\n          middleName\n          address\n          birthDate\n          contact\n          employeeID\n          gender\n          title\n          id\n        }\n      }\n        meta {\n          currentPage\n          lastPage\n          next\n          perPage\n          prev\n          total\n        }\n      }\n  }\n": typeof types.FindAllUsersDocument,
    "\n  query MeQuery {\n    meQuery {\n      user {\n        id\n        departmentId\n        email\n        username\n        createdAt\n        department {\n          name\n          id\n          description\n        }\n        profile {\n          address\n          birthDate\n          contact\n          createdAt\n          employeeID\n          firstName\n          gender\n          id\n          lastName\n          middleName\n          title\n          avatar\n        }\n        role\n      }\n      isSignedIn\n    }\n  }\n": typeof types.MeQueryDocument,
};
const documents: Documents = {
    "\n  mutation CreateDepartment($payload: CreateDepartmentInput!) {\n    createDepartment(payload: $payload) {\n      message\n    }\n  }\n": types.CreateDepartmentDocument,
    "\n  mutation UpdateDepartment($updateDepartmentId: String!, $payload: UpdateDepartmentInput!) {\n    updateDepartment(id: $updateDepartmentId, payload: $payload) {\n      message\n    }\n  }\n": types.UpdateDepartmentDocument,
    "\n    mutation DeleteDepartment($deleteDepartmentId: String!) {\n        deleteDepartment(id: $deleteDepartmentId) {\n            message\n        }\n    }\n": types.DeleteDepartmentDocument,
    "\n  mutation CreateEvent($payload: CreateEventInput!) {\n    createEvent(payload: $payload) {\n      message\n    }\n  }\n": types.CreateEventDocument,
    "\n  mutation UpdateEvent($updateEventId: String!, $payload: UpdateEventInput!) {\n    updateEvent(id: $updateEventId, payload: $payload) {\n      message\n    }\n  }\n": types.UpdateEventDocument,
    "\n  mutation DeleteEvent($deleteEventId: String!) {\n    deleteEvent(id: $deleteEventId) {\n      message\n    }\n  }\n": types.DeleteEventDocument,
    "\n  mutation CreatePost($payload: CreatePostInput!) {\n    createPost(payload: $payload) {\n      message\n    }\n  }\n": types.CreatePostDocument,
    "\n  mutation UpdatePost($data: UpdatePostInput!, $postId: String!) {\n    updatePost(data: $data, postId: $postId) {\n      message\n    }\n  }\n": types.UpdatePostDocument,
    "\n  mutation DeletePost($postId: String!) {\n    deletePost(postId: $postId) {\n      message\n    }\n  }\n": types.DeletePostDocument,
    "\n    mutation UpdateProfile($updateProfileId: String!, $payload: UpdateProfileInput!) {\n        updateProfile(id: $updateProfileId, payload: $payload) {\n            message\n        }\n    }\n": types.UpdateProfileDocument,
    "\n  mutation CreateTicket($payload: CreateTicketInput!) {\n    createTicket(payload: $payload) {\n      message\n    }\n  }\n": types.CreateTicketDocument,
    "\n  mutation UpdateTicket(\n    $updateTicketId: String!\n    $payload: UpdateTicketInput!\n  ) {\n    updateTicket(id: $updateTicketId, payload: $payload) {\n      message\n    }\n  }\n": types.UpdateTicketDocument,
    "\n  mutation DeleteTicket($deleteTicketId: String!) {\n    deleteTicket(id: $deleteTicketId) {\n      message\n    }\n  }\n": types.DeleteTicketDocument,
    "\n  # mutation Mutation($signInInput: SignInInput!) {\n  #   signin(signInInput: $signInInput) {\n  #     accessToken\n  #   }\n  # }\n  mutation Mutation($signInInput: SignInInput!) {\n    signin(signInInput: $signInInput) {\n      user {\n        id\n        role\n        profile {\n          id\n          firstName\n          middleName\n          lastName\n        }\n      }\n      isSignedIn\n    }\n  }\n": types.MutationDocument,
    "\n  mutation LogOut {\n    logOut {\n      message\n    }\n  }\n": types.LogOutDocument,
    "\n  mutation CreateUser($payload: CreateUserInput!) {\n    createUser(payload: $payload) {\n      message\n    }\n  }\n": types.CreateUserDocument,
    "\n  mutation UpdateUser($updateUserId: String!, $payload: UpdateUserInput!) {\n    updateUser(id: $updateUserId, payload: $payload) {\n      message\n    }\n  }\n": types.UpdateUserDocument,
    "\n  mutation DeleteUser($deleteUserId: String!) {\n    deleteUser(id: $deleteUserId) {\n      message\n    }\n  }\n": types.DeleteUserDocument,
    "\n  query GetCensusSummary {\n    getCensusSummary {\n      departmentsWithUserCount {\n        departmentId\n        departmentName\n        userCount\n        departmentDescription\n      }\n      ticketsByStatus {\n        count\n        status\n      }\n      totalEvents\n      totalDepartments\n      totalTickets\n      totalUsers\n      totalPosts\n    }\n  }\n": types.GetCensusSummaryDocument,
    "\n  query GetTicketData($userId: String!) {\n    getCensusSummary(userId: $userId) {\n      ticketByUserId {\n        status\n        count\n      }\n      totalTicketsByUserId\n    }\n  }\n": types.GetTicketDataDocument,
    "\n  query FindAllDepartments($page: Int, $perPage: Int) {\n    findAllDepartments(page: $page, perPage: $perPage) {\n      data {\n        description\n        id\n        name\n        createdAt\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": types.FindAllDepartmentsDocument,
    "\n  query FindAllForDropdown {\n    findAllForDropdown {\n      id\n      name\n      description\n    }\n  }\n": types.FindAllForDropdownDocument,
    "\n  query FindAllEvents($page: Int, $perPage: Int) {\n    findAllEvents(page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        detailsUrl\n        endDate\n        id\n        location\n        startDate\n        title\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": types.FindAllEventsDocument,
    "\n  query FindAllPosts($page: Int, $perPage: Int) {\n    findAllPosts(page: $page, perPage: $perPage) {\n      data {\n        datePosted\n        content\n        id\n        images\n        user {\n          id\n          profile {\n            lastName\n            firstName\n            avatar\n          }\n          department {\n            name\n            description\n          }\n          username\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": types.FindAllPostsDocument,
    "\n  query FindAllTickets($where: TicketWhereInput, $page: Int, $perPage: Int) {\n    findAllTickets(where: $where, page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n        floor\n        subject\n        remarks\n        message\n        id\n        missedAt\n        screenshot\n        statusFormatted\n        status\n        updatedBy\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": types.FindAllTicketsDocument,
    "\n  query FindTicketsByUser($userId: String!, $perPage: Int, $page: Int) {\n    findTicketsByUser(userId: $userId, perPage: $perPage, page: $page) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        floor\n        id\n        subject\n        statusFormatted\n        remarks\n        missedAt\n        screenshot\n        status\n        updatedBy\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n": types.FindTicketsByUserDocument,
    "\n  query FindTicketLogs($findTicketbyIdId: String!) {\n    findTicketbyID(id: $findTicketbyIdId) {\n      auditLogs {\n        action\n        ticketId\n        timestamp\n        updatedBy\n        remarks\n        id\n      }\n    }\n  }\n": types.FindTicketLogsDocument,
    "\n  query FindTicketsWorkedByUser($userId: String!) {\n    findTicketsWorkedByUser(userId: $userId) {\n      data {\n        subject\n        status\n        statusFormatted\n        missedAt\n        remarks\n        message\n        screenshot\n        updatedBy\n        id\n        floor\n        createdById\n        createdAt\n        createdBy {\n          username\n          profile {\n            firstName\n            lastName\n          }\n        }\n      }\n    }\n  }\n": types.FindTicketsWorkedByUserDocument,
    "\n  query FindTicketsByDepartment($page: Int, $perPage: Int, $search: String) {\n    findTicketsByDepartment(page: $page, perPage: $perPage, search: $search) {\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n      data {\n        id\n        subject\n        message\n        status\n        statusFormatted\n        createdAt\n        updatedAt\n        missedAt\n        remarks\n        screenshot\n        floor\n        createdBy {\n          username\n          profile {\n            firstName\n            middleName\n            lastName\n          }\n        }\n        createdById\n        updatedBy\n        departmentId\n        department {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n": types.FindTicketsByDepartmentDocument,
    "\n  query FindAllUsers($page: Int, $perPage: Int) {\n      findAllUsers(perPage: $perPage, page: $page) {\n        data {\n        email\n        id\n        role\n        username\n        createdAt\n        department {\n          name\n          id\n        }\n        profile {\n          firstName\n          lastName\n          middleName\n          address\n          birthDate\n          contact\n          employeeID\n          gender\n          title\n          id\n        }\n      }\n        meta {\n          currentPage\n          lastPage\n          next\n          perPage\n          prev\n          total\n        }\n      }\n  }\n": types.FindAllUsersDocument,
    "\n  query MeQuery {\n    meQuery {\n      user {\n        id\n        departmentId\n        email\n        username\n        createdAt\n        department {\n          name\n          id\n          description\n        }\n        profile {\n          address\n          birthDate\n          contact\n          createdAt\n          employeeID\n          firstName\n          gender\n          id\n          lastName\n          middleName\n          title\n          avatar\n        }\n        role\n      }\n      isSignedIn\n    }\n  }\n": types.MeQueryDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateDepartment($payload: CreateDepartmentInput!) {\n    createDepartment(payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation CreateDepartment($payload: CreateDepartmentInput!) {\n    createDepartment(payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateDepartment($updateDepartmentId: String!, $payload: UpdateDepartmentInput!) {\n    updateDepartment(id: $updateDepartmentId, payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateDepartment($updateDepartmentId: String!, $payload: UpdateDepartmentInput!) {\n    updateDepartment(id: $updateDepartmentId, payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteDepartment($deleteDepartmentId: String!) {\n        deleteDepartment(id: $deleteDepartmentId) {\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteDepartment($deleteDepartmentId: String!) {\n        deleteDepartment(id: $deleteDepartmentId) {\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateEvent($payload: CreateEventInput!) {\n    createEvent(payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation CreateEvent($payload: CreateEventInput!) {\n    createEvent(payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateEvent($updateEventId: String!, $payload: UpdateEventInput!) {\n    updateEvent(id: $updateEventId, payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateEvent($updateEventId: String!, $payload: UpdateEventInput!) {\n    updateEvent(id: $updateEventId, payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteEvent($deleteEventId: String!) {\n    deleteEvent(id: $deleteEventId) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteEvent($deleteEventId: String!) {\n    deleteEvent(id: $deleteEventId) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreatePost($payload: CreatePostInput!) {\n    createPost(payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePost($payload: CreatePostInput!) {\n    createPost(payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdatePost($data: UpdatePostInput!, $postId: String!) {\n    updatePost(data: $data, postId: $postId) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation UpdatePost($data: UpdatePostInput!, $postId: String!) {\n    updatePost(data: $data, postId: $postId) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeletePost($postId: String!) {\n    deletePost(postId: $postId) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation DeletePost($postId: String!) {\n    deletePost(postId: $postId) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateProfile($updateProfileId: String!, $payload: UpdateProfileInput!) {\n        updateProfile(id: $updateProfileId, payload: $payload) {\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateProfile($updateProfileId: String!, $payload: UpdateProfileInput!) {\n        updateProfile(id: $updateProfileId, payload: $payload) {\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateTicket($payload: CreateTicketInput!) {\n    createTicket(payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation CreateTicket($payload: CreateTicketInput!) {\n    createTicket(payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateTicket(\n    $updateTicketId: String!\n    $payload: UpdateTicketInput!\n  ) {\n    updateTicket(id: $updateTicketId, payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateTicket(\n    $updateTicketId: String!\n    $payload: UpdateTicketInput!\n  ) {\n    updateTicket(id: $updateTicketId, payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteTicket($deleteTicketId: String!) {\n    deleteTicket(id: $deleteTicketId) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteTicket($deleteTicketId: String!) {\n    deleteTicket(id: $deleteTicketId) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  # mutation Mutation($signInInput: SignInInput!) {\n  #   signin(signInInput: $signInInput) {\n  #     accessToken\n  #   }\n  # }\n  mutation Mutation($signInInput: SignInInput!) {\n    signin(signInInput: $signInInput) {\n      user {\n        id\n        role\n        profile {\n          id\n          firstName\n          middleName\n          lastName\n        }\n      }\n      isSignedIn\n    }\n  }\n"): (typeof documents)["\n  # mutation Mutation($signInInput: SignInInput!) {\n  #   signin(signInInput: $signInInput) {\n  #     accessToken\n  #   }\n  # }\n  mutation Mutation($signInInput: SignInInput!) {\n    signin(signInInput: $signInInput) {\n      user {\n        id\n        role\n        profile {\n          id\n          firstName\n          middleName\n          lastName\n        }\n      }\n      isSignedIn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation LogOut {\n    logOut {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation LogOut {\n    logOut {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateUser($payload: CreateUserInput!) {\n    createUser(payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation CreateUser($payload: CreateUserInput!) {\n    createUser(payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateUser($updateUserId: String!, $payload: UpdateUserInput!) {\n    updateUser(id: $updateUserId, payload: $payload) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateUser($updateUserId: String!, $payload: UpdateUserInput!) {\n    updateUser(id: $updateUserId, payload: $payload) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteUser($deleteUserId: String!) {\n    deleteUser(id: $deleteUserId) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteUser($deleteUserId: String!) {\n    deleteUser(id: $deleteUserId) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCensusSummary {\n    getCensusSummary {\n      departmentsWithUserCount {\n        departmentId\n        departmentName\n        userCount\n        departmentDescription\n      }\n      ticketsByStatus {\n        count\n        status\n      }\n      totalEvents\n      totalDepartments\n      totalTickets\n      totalUsers\n      totalPosts\n    }\n  }\n"): (typeof documents)["\n  query GetCensusSummary {\n    getCensusSummary {\n      departmentsWithUserCount {\n        departmentId\n        departmentName\n        userCount\n        departmentDescription\n      }\n      ticketsByStatus {\n        count\n        status\n      }\n      totalEvents\n      totalDepartments\n      totalTickets\n      totalUsers\n      totalPosts\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetTicketData($userId: String!) {\n    getCensusSummary(userId: $userId) {\n      ticketByUserId {\n        status\n        count\n      }\n      totalTicketsByUserId\n    }\n  }\n"): (typeof documents)["\n  query GetTicketData($userId: String!) {\n    getCensusSummary(userId: $userId) {\n      ticketByUserId {\n        status\n        count\n      }\n      totalTicketsByUserId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindAllDepartments($page: Int, $perPage: Int) {\n    findAllDepartments(page: $page, perPage: $perPage) {\n      data {\n        description\n        id\n        name\n        createdAt\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindAllDepartments($page: Int, $perPage: Int) {\n    findAllDepartments(page: $page, perPage: $perPage) {\n      data {\n        description\n        id\n        name\n        createdAt\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindAllForDropdown {\n    findAllForDropdown {\n      id\n      name\n      description\n    }\n  }\n"): (typeof documents)["\n  query FindAllForDropdown {\n    findAllForDropdown {\n      id\n      name\n      description\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindAllEvents($page: Int, $perPage: Int) {\n    findAllEvents(page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        detailsUrl\n        endDate\n        id\n        location\n        startDate\n        title\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindAllEvents($page: Int, $perPage: Int) {\n    findAllEvents(page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        detailsUrl\n        endDate\n        id\n        location\n        startDate\n        title\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindAllPosts($page: Int, $perPage: Int) {\n    findAllPosts(page: $page, perPage: $perPage) {\n      data {\n        datePosted\n        content\n        id\n        images\n        user {\n          id\n          profile {\n            lastName\n            firstName\n            avatar\n          }\n          department {\n            name\n            description\n          }\n          username\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindAllPosts($page: Int, $perPage: Int) {\n    findAllPosts(page: $page, perPage: $perPage) {\n      data {\n        datePosted\n        content\n        id\n        images\n        user {\n          id\n          profile {\n            lastName\n            firstName\n            avatar\n          }\n          department {\n            name\n            description\n          }\n          username\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindAllTickets($where: TicketWhereInput, $page: Int, $perPage: Int) {\n    findAllTickets(where: $where, page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n        floor\n        subject\n        remarks\n        message\n        id\n        missedAt\n        screenshot\n        statusFormatted\n        status\n        updatedBy\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindAllTickets($where: TicketWhereInput, $page: Int, $perPage: Int) {\n    findAllTickets(where: $where, page: $page, perPage: $perPage) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n        floor\n        subject\n        remarks\n        message\n        id\n        missedAt\n        screenshot\n        statusFormatted\n        status\n        updatedBy\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindTicketsByUser($userId: String!, $perPage: Int, $page: Int) {\n    findTicketsByUser(userId: $userId, perPage: $perPage, page: $page) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        floor\n        id\n        subject\n        statusFormatted\n        remarks\n        missedAt\n        screenshot\n        status\n        updatedBy\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindTicketsByUser($userId: String!, $perPage: Int, $page: Int) {\n    findTicketsByUser(userId: $userId, perPage: $perPage, page: $page) {\n      data {\n        createdAt\n        createdBy {\n          username\n          profile {\n            lastName\n            middleName\n            firstName\n          }\n        }\n        floor\n        id\n        subject\n        statusFormatted\n        remarks\n        missedAt\n        screenshot\n        status\n        updatedBy\n        createdById\n        departmentId\n        department {\n          name\n          id\n        }\n      }\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindTicketLogs($findTicketbyIdId: String!) {\n    findTicketbyID(id: $findTicketbyIdId) {\n      auditLogs {\n        action\n        ticketId\n        timestamp\n        updatedBy\n        remarks\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindTicketLogs($findTicketbyIdId: String!) {\n    findTicketbyID(id: $findTicketbyIdId) {\n      auditLogs {\n        action\n        ticketId\n        timestamp\n        updatedBy\n        remarks\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindTicketsWorkedByUser($userId: String!) {\n    findTicketsWorkedByUser(userId: $userId) {\n      data {\n        subject\n        status\n        statusFormatted\n        missedAt\n        remarks\n        message\n        screenshot\n        updatedBy\n        id\n        floor\n        createdById\n        createdAt\n        createdBy {\n          username\n          profile {\n            firstName\n            lastName\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindTicketsWorkedByUser($userId: String!) {\n    findTicketsWorkedByUser(userId: $userId) {\n      data {\n        subject\n        status\n        statusFormatted\n        missedAt\n        remarks\n        message\n        screenshot\n        updatedBy\n        id\n        floor\n        createdById\n        createdAt\n        createdBy {\n          username\n          profile {\n            firstName\n            lastName\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindTicketsByDepartment($page: Int, $perPage: Int, $search: String) {\n    findTicketsByDepartment(page: $page, perPage: $perPage, search: $search) {\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n      data {\n        id\n        subject\n        message\n        status\n        statusFormatted\n        createdAt\n        updatedAt\n        missedAt\n        remarks\n        screenshot\n        floor\n        createdBy {\n          username\n          profile {\n            firstName\n            middleName\n            lastName\n          }\n        }\n        createdById\n        updatedBy\n        departmentId\n        department {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindTicketsByDepartment($page: Int, $perPage: Int, $search: String) {\n    findTicketsByDepartment(page: $page, perPage: $perPage, search: $search) {\n      meta {\n        currentPage\n        lastPage\n        next\n        perPage\n        prev\n        total\n      }\n      data {\n        id\n        subject\n        message\n        status\n        statusFormatted\n        createdAt\n        updatedAt\n        missedAt\n        remarks\n        screenshot\n        floor\n        createdBy {\n          username\n          profile {\n            firstName\n            middleName\n            lastName\n          }\n        }\n        createdById\n        updatedBy\n        departmentId\n        department {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FindAllUsers($page: Int, $perPage: Int) {\n      findAllUsers(perPage: $perPage, page: $page) {\n        data {\n        email\n        id\n        role\n        username\n        createdAt\n        department {\n          name\n          id\n        }\n        profile {\n          firstName\n          lastName\n          middleName\n          address\n          birthDate\n          contact\n          employeeID\n          gender\n          title\n          id\n        }\n      }\n        meta {\n          currentPage\n          lastPage\n          next\n          perPage\n          prev\n          total\n        }\n      }\n  }\n"): (typeof documents)["\n  query FindAllUsers($page: Int, $perPage: Int) {\n      findAllUsers(perPage: $perPage, page: $page) {\n        data {\n        email\n        id\n        role\n        username\n        createdAt\n        department {\n          name\n          id\n        }\n        profile {\n          firstName\n          lastName\n          middleName\n          address\n          birthDate\n          contact\n          employeeID\n          gender\n          title\n          id\n        }\n      }\n        meta {\n          currentPage\n          lastPage\n          next\n          perPage\n          prev\n          total\n        }\n      }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MeQuery {\n    meQuery {\n      user {\n        id\n        departmentId\n        email\n        username\n        createdAt\n        department {\n          name\n          id\n          description\n        }\n        profile {\n          address\n          birthDate\n          contact\n          createdAt\n          employeeID\n          firstName\n          gender\n          id\n          lastName\n          middleName\n          title\n          avatar\n        }\n        role\n      }\n      isSignedIn\n    }\n  }\n"): (typeof documents)["\n  query MeQuery {\n    meQuery {\n      user {\n        id\n        departmentId\n        email\n        username\n        createdAt\n        department {\n          name\n          id\n          description\n        }\n        profile {\n          address\n          birthDate\n          contact\n          createdAt\n          employeeID\n          firstName\n          gender\n          id\n          lastName\n          middleName\n          title\n          avatar\n        }\n        role\n      }\n      isSignedIn\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;